default_method_hyperparameters:
  targets_path: ./data/optimizer_targets/extra_targets/advbench_subset_targets.json
  # masking_model: gpt-4-0613
  # masking_model_key: your-key-here
  masking_model: 
    model_name_or_path: /data/hzq/models/vicuna1.5_13b
    trust_remote_code: True
    num_gpus: 1
    dtype: bfloat16
  masking_direction: horizontal # "vertical"
  fontname: cards # ['gen', 'alphabet','letters','keyboard','cards','puzzle','gen']

<model_name1>:
  target_model: <model_name1>['model']

